source 'http://rubygems.org'

gem 'rake'
gem 'dashing'
gem 'dotenv'
gem 'octokit'
gem 'i18n'
gem 'faraday'
gem 'httparty'
gem 'twitter', '>= 5.0.0'
gem 'travis'
gem 'google-api-client'
gem 'github_api'
